spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  main:
    web-application-type: servlet

jwt:
  secret-key: "${JWT_SECRET_KEY}"
  access-token-validity-in-seconds: 600
  refresh-token-validity-in-seconds: 1209600

logging:
  level:
    com.whalewatch.service: DEBUG
