plugins {
    id 'java' // Java 플러그인 추가 (Java 프로젝트로 인식)
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group 'com.whalewatch'
version '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()  // Maven Central 레포지토리에서 라이브러리 다운로드
}

subprojects {
    // 모든 서브프로젝트에 공통 적용할 설정
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    repositories {
        mavenCentral() // Maven Central에서 의존성 다운로드
    }

    dependencies {
        implementation 'mysql:mysql-connector-java:8.0.33'
    }


    test {
        useJUnitPlatform() //JUnit 테스트 플랫폼 사용
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

}


