server:
  port: 8083

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9093}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.whalewatch.transactionservice: DEBUG
